port: 8844  # 监听端口
hostname: 127.0.0.1  # 监听 IP
version: 0.0.5  # Yoeth 版本
plugins:
  - path: ./plugin/ping.js
    disable: false
    config: null
  - path: ./plugin/log.js
    disable: false
    config: null